/**
 * Fifty Truck API
 * This is the API of fifty truck
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@fiftytruck.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { FleetDriver } from '../model/FleetDriver';
import { FleetDriverActivity } from '../model/FleetDriverActivity';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ApiFmsService {

    protected basePath = 'http://api-inte.fiftytruck.com/api/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get driver detail
     * 
     * @param carrierId Carrier id
     * @param driverExternalId Driver external id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDriverDetail(carrierId: number, driverExternalId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<FleetDriverActivity>>;
    public getDriverDetail(carrierId: number, driverExternalId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<FleetDriverActivity>>>;
    public getDriverDetail(carrierId: number, driverExternalId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<FleetDriverActivity>>>;
    public getDriverDetail(carrierId: number, driverExternalId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (carrierId === null || carrierId === undefined) {
            throw new Error('Required parameter carrierId was null or undefined when calling getDriverDetail.');
        }

        if (driverExternalId === null || driverExternalId === undefined) {
            throw new Error('Required parameter driverExternalId was null or undefined when calling getDriverDetail.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<FleetDriverActivity>>(`${this.basePath}/fms/fleet/${encodeURIComponent(String(carrierId))}/driverExternalId/${encodeURIComponent(String(driverExternalId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get fleet infos
     * 
     * @param carrierId Carrier id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFleet(carrierId: number, observe?: 'body', reportProgress?: boolean): Observable<Array<FleetDriver>>;
    public getFleet(carrierId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<FleetDriver>>>;
    public getFleet(carrierId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<FleetDriver>>>;
    public getFleet(carrierId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (carrierId === null || carrierId === undefined) {
            throw new Error('Required parameter carrierId was null or undefined when calling getFleet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<FleetDriver>>(`${this.basePath}/fms/fleet/${encodeURIComponent(String(carrierId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
