<?php
/**
 * CarrierTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fifty Truck API
 *
 * This is the API of fifty truck
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@fiftytruck.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CarrierTest Class Doc Comment
 *
 * @category    Class
 * @description Carrier
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CarrierTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Carrier"
     */
    public function testCarrier()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "is_approved"
     */
    public function testPropertyIsApproved()
    {
    }

    /**
     * Test attribute "tms_connected"
     */
    public function testPropertyTmsConnected()
    {
    }

    /**
     * Test attribute "fms_connected"
     */
    public function testPropertyFmsConnected()
    {
    }

    /**
     * Test attribute "head_office_address_street_name"
     */
    public function testPropertyHeadOfficeAddressStreetName()
    {
    }

    /**
     * Test attribute "head_office_address_postcode"
     */
    public function testPropertyHeadOfficeAddressPostcode()
    {
    }

    /**
     * Test attribute "head_office_address_city"
     */
    public function testPropertyHeadOfficeAddressCity()
    {
    }

    /**
     * Test attribute "head_office_address_country"
     */
    public function testPropertyHeadOfficeAddressCountry()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }
}
