<?php
/**
 * FleetDriverActivityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fifty Truck API
 *
 * This is the API of fifty truck
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@fiftytruck.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FleetDriverActivityTest Class Doc Comment
 *
 * @category    Class
 * @description FleetDriverActivity
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FleetDriverActivityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FleetDriverActivity"
     */
    public function testFleetDriverActivity()
    {
    }

    /**
     * Test attribute "carrier_id"
     */
    public function testPropertyCarrierId()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "current_activity"
     */
    public function testPropertyCurrentActivity()
    {
    }

    /**
     * Test attribute "current_activity_date"
     */
    public function testPropertyCurrentActivityDate()
    {
    }

    /**
     * Test attribute "current_gps_coordinates"
     */
    public function testPropertyCurrentGpsCoordinates()
    {
    }

    /**
     * Test attribute "polyline"
     */
    public function testPropertyPolyline()
    {
    }
}
