<?php
/**
 * GeocodedAddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fifty Truck API
 *
 * This is the API of fifty truck
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@fiftytruck.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GeocodedAddressTest Class Doc Comment
 *
 * @category    Class
 * @description GeocodedAddress
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GeocodedAddressTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GeocodedAddress"
     */
    public function testGeocodedAddress()
    {
    }

    /**
     * Test attribute "gps_coordinates"
     */
    public function testPropertyGpsCoordinates()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "street_name"
     */
    public function testPropertyStreetName()
    {
    }

    /**
     * Test attribute "complement"
     */
    public function testPropertyComplement()
    {
    }

    /**
     * Test attribute "post_code"
     */
    public function testPropertyPostCode()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {
    }

    /**
     * Test attribute "administrative_level1_name"
     */
    public function testPropertyAdministrativeLevel1Name()
    {
    }

    /**
     * Test attribute "administrative_level1_code"
     */
    public function testPropertyAdministrativeLevel1Code()
    {
    }

    /**
     * Test attribute "administrative_level2_name"
     */
    public function testPropertyAdministrativeLevel2Name()
    {
    }

    /**
     * Test attribute "administrative_level2_code"
     */
    public function testPropertyAdministrativeLevel2Code()
    {
    }

    /**
     * Test attribute "administrative_level3_name"
     */
    public function testPropertyAdministrativeLevel3Name()
    {
    }

    /**
     * Test attribute "administrative_level3_code"
     */
    public function testPropertyAdministrativeLevel3Code()
    {
    }
}
