<?php
/**
 * MarketplaceOfferTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fifty Truck API
 *
 * This is the API of fifty truck
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@fiftytruck.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MarketplaceOfferTest Class Doc Comment
 *
 * @category    Class
 * @description MarketplaceOffer
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MarketplaceOfferTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MarketplaceOffer"
     */
    public function testMarketplaceOffer()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "operator_id"
     */
    public function testPropertyOperatorId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "automatic_refresh"
     */
    public function testPropertyAutomaticRefresh()
    {
    }

    /**
     * Test attribute "complementary_informations"
     */
    public function testPropertyComplementaryInformations()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "good_type"
     */
    public function testPropertyGoodType()
    {
    }

    /**
     * Test attribute "truck_types"
     */
    public function testPropertyTruckTypes()
    {
    }

    /**
     * Test attribute "needed_equipments"
     */
    public function testPropertyNeededEquipments()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "picking_date_start"
     */
    public function testPropertyPickingDateStart()
    {
    }

    /**
     * Test attribute "picking_date_end"
     */
    public function testPropertyPickingDateEnd()
    {
    }

    /**
     * Test attribute "picking_time_start"
     */
    public function testPropertyPickingTimeStart()
    {
    }

    /**
     * Test attribute "picking_time_end"
     */
    public function testPropertyPickingTimeEnd()
    {
    }

    /**
     * Test attribute "desired_delivery_date_start"
     */
    public function testPropertyDesiredDeliveryDateStart()
    {
    }

    /**
     * Test attribute "desired_delivery_date_end"
     */
    public function testPropertyDesiredDeliveryDateEnd()
    {
    }

    /**
     * Test attribute "desired_delivery_time_start"
     */
    public function testPropertyDesiredDeliveryTimeStart()
    {
    }

    /**
     * Test attribute "desired_delivery_time_end"
     */
    public function testPropertyDesiredDeliveryTimeEnd()
    {
    }

    /**
     * Test attribute "scheduled_date"
     */
    public function testPropertyScheduledDate()
    {
    }

    /**
     * Test attribute "loading_point_contact_first_name"
     */
    public function testPropertyLoadingPointContactFirstName()
    {
    }

    /**
     * Test attribute "loading_point_contact_last_name"
     */
    public function testPropertyLoadingPointContactLastName()
    {
    }

    /**
     * Test attribute "loading_point_contact_company_name"
     */
    public function testPropertyLoadingPointContactCompanyName()
    {
    }

    /**
     * Test attribute "loading_point_contact_phone_number"
     */
    public function testPropertyLoadingPointContactPhoneNumber()
    {
    }

    /**
     * Test attribute "loading_point_contact_cellphone_number"
     */
    public function testPropertyLoadingPointContactCellphoneNumber()
    {
    }

    /**
     * Test attribute "loading_point_contact_email"
     */
    public function testPropertyLoadingPointContactEmail()
    {
    }

    /**
     * Test attribute "loading_point_address_number"
     */
    public function testPropertyLoadingPointAddressNumber()
    {
    }

    /**
     * Test attribute "loading_point_address_street_name"
     */
    public function testPropertyLoadingPointAddressStreetName()
    {
    }

    /**
     * Test attribute "loading_point_address_complement"
     */
    public function testPropertyLoadingPointAddressComplement()
    {
    }

    /**
     * Test attribute "loading_point_address_postcode"
     */
    public function testPropertyLoadingPointAddressPostcode()
    {
    }

    /**
     * Test attribute "loading_point_address_zone"
     */
    public function testPropertyLoadingPointAddressZone()
    {
    }

    /**
     * Test attribute "loading_point_address_city"
     */
    public function testPropertyLoadingPointAddressCity()
    {
    }

    /**
     * Test attribute "loading_point_address_country"
     */
    public function testPropertyLoadingPointAddressCountry()
    {
    }

    /**
     * Test attribute "loading_point_address_country_code"
     */
    public function testPropertyLoadingPointAddressCountryCode()
    {
    }

    /**
     * Test attribute "loading_point_address_gps_coordinates"
     */
    public function testPropertyLoadingPointAddressGpsCoordinates()
    {
    }

    /**
     * Test attribute "unloading_point_contact_first_name"
     */
    public function testPropertyUnloadingPointContactFirstName()
    {
    }

    /**
     * Test attribute "unloading_point_contact_last_name"
     */
    public function testPropertyUnloadingPointContactLastName()
    {
    }

    /**
     * Test attribute "unloading_point_contact_company_name"
     */
    public function testPropertyUnloadingPointContactCompanyName()
    {
    }

    /**
     * Test attribute "unloading_point_contact_phone_number"
     */
    public function testPropertyUnloadingPointContactPhoneNumber()
    {
    }

    /**
     * Test attribute "unloading_point_contact_cellphone_number"
     */
    public function testPropertyUnloadingPointContactCellphoneNumber()
    {
    }

    /**
     * Test attribute "unloading_point_contact_email"
     */
    public function testPropertyUnloadingPointContactEmail()
    {
    }

    /**
     * Test attribute "unloading_point_address_number"
     */
    public function testPropertyUnloadingPointAddressNumber()
    {
    }

    /**
     * Test attribute "unloading_point_address_street_name"
     */
    public function testPropertyUnloadingPointAddressStreetName()
    {
    }

    /**
     * Test attribute "unloading_point_address_complement"
     */
    public function testPropertyUnloadingPointAddressComplement()
    {
    }

    /**
     * Test attribute "unloading_point_address_postcode"
     */
    public function testPropertyUnloadingPointAddressPostcode()
    {
    }

    /**
     * Test attribute "unloading_point_address_zone"
     */
    public function testPropertyUnloadingPointAddressZone()
    {
    }

    /**
     * Test attribute "unloading_point_address_city"
     */
    public function testPropertyUnloadingPointAddressCity()
    {
    }

    /**
     * Test attribute "unloading_point_address_country"
     */
    public function testPropertyUnloadingPointAddressCountry()
    {
    }

    /**
     * Test attribute "unloading_point_address_country_code"
     */
    public function testPropertyUnloadingPointAddressCountryCode()
    {
    }

    /**
     * Test attribute "unloading_point_address_gps_coordinates"
     */
    public function testPropertyUnloadingPointAddressGpsCoordinates()
    {
    }

    /**
     * Test attribute "product_group"
     */
    public function testPropertyProductGroup()
    {
    }

    /**
     * Test attribute "is_hazardous_product"
     */
    public function testPropertyIsHazardousProduct()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "deleted_at"
     */
    public function testPropertyDeletedAt()
    {
    }

    /**
     * Test attribute "marketplace_offer_publications"
     */
    public function testPropertyMarketplaceOfferPublications()
    {
    }
}
