<?php
/**
 * SearchRouteTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fifty Truck API
 *
 * This is the API of fifty truck
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@fiftytruck.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SearchRouteTest Class Doc Comment
 *
 * @category    Class
 * @description SearchRoute
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SearchRouteTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SearchRoute"
     */
    public function testSearchRoute()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "shipping_order_search_id"
     */
    public function testPropertyShippingOrderSearchId()
    {
    }

    /**
     * Test attribute "search_terms"
     */
    public function testPropertySearchTerms()
    {
    }

    /**
     * Test attribute "computed_search_zones"
     */
    public function testPropertyComputedSearchZones()
    {
    }

    /**
     * Test attribute "route_with_toll"
     */
    public function testPropertyRouteWithToll()
    {
    }

    /**
     * Test attribute "route_without_toll"
     */
    public function testPropertyRouteWithoutToll()
    {
    }

    /**
     * Test attribute "waypoints"
     */
    public function testPropertyWaypoints()
    {
    }
}
