<?php
/**
 * ShippingOrderGroupingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fifty Truck API
 *
 * This is the API of fifty truck
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@fiftytruck.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ShippingOrderGroupingTest Class Doc Comment
 *
 * @category    Class
 * @description ShippingOrderGrouping
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShippingOrderGroupingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShippingOrderGrouping"
     */
    public function testShippingOrderGrouping()
    {
    }

    /**
     * Test attribute "shipping_order_result"
     */
    public function testPropertyShippingOrderResult()
    {
    }

    /**
     * Test attribute "shipping_order_result_complement"
     */
    public function testPropertyShippingOrderResultComplement()
    {
    }

    /**
     * Test attribute "route_estimation"
     */
    public function testPropertyRouteEstimation()
    {
    }

    /**
     * Test attribute "scores"
     */
    public function testPropertyScores()
    {
    }

    /**
     * Test attribute "is_complement_before"
     */
    public function testPropertyIsComplementBefore()
    {
    }

    /**
     * Test attribute "is_without_toll"
     */
    public function testPropertyIsWithoutToll()
    {
    }
}
