<?php
/**
 * SearchRouteComputedSearchZonesUnloadingPointAddressZones
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fifty Truck API
 *
 * This is the API of fifty truck
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@fiftytruck.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SearchRouteComputedSearchZonesUnloadingPointAddressZones Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SearchRouteComputedSearchZonesUnloadingPointAddressZones implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SearchRoute_computedSearchZones_unloadingPointAddressZones';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'country_code' => 'string',
        'zone' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'country_code' => null,
        'zone' => 'string'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'country_code' => 'countryCode',
        'zone' => 'zone'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'country_code' => 'setCountryCode',
        'zone' => 'setZone'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'country_code' => 'getCountryCode',
        'zone' => 'getZone'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const COUNTRY_CODE_AD = 'AD';
    const COUNTRY_CODE_AL = 'AL';
    const COUNTRY_CODE_AT = 'AT';
    const COUNTRY_CODE_BA = 'BA';
    const COUNTRY_CODE_BE = 'BE';
    const COUNTRY_CODE_BG = 'BG';
    const COUNTRY_CODE_BY = 'BY';
    const COUNTRY_CODE_CH = 'CH';
    const COUNTRY_CODE_CY = 'CY';
    const COUNTRY_CODE_CZ = 'CZ';
    const COUNTRY_CODE_DE = 'DE';
    const COUNTRY_CODE_DK = 'DK';
    const COUNTRY_CODE_EE = 'EE';
    const COUNTRY_CODE_ES = 'ES';
    const COUNTRY_CODE_FI = 'FI';
    const COUNTRY_CODE_FO = 'FO';
    const COUNTRY_CODE_FR = 'FR';
    const COUNTRY_CODE_GB = 'GB';
    const COUNTRY_CODE_GI = 'GI';
    const COUNTRY_CODE_GR = 'GR';
    const COUNTRY_CODE_HR = 'HR';
    const COUNTRY_CODE_HU = 'HU';
    const COUNTRY_CODE_IE = 'IE';
    const COUNTRY_CODE_IM = 'IM';
    const COUNTRY_CODE_IS = 'IS';
    const COUNTRY_CODE_IT = 'IT';
    const COUNTRY_CODE_LI = 'LI';
    const COUNTRY_CODE_LT = 'LT';
    const COUNTRY_CODE_LU = 'LU';
    const COUNTRY_CODE_LV = 'LV';
    const COUNTRY_CODE_MC = 'MC';
    const COUNTRY_CODE_MD = 'MD';
    const COUNTRY_CODE_ME = 'ME';
    const COUNTRY_CODE_MK = 'MK';
    const COUNTRY_CODE_MT = 'MT';
    const COUNTRY_CODE_NL = 'NL';
    const COUNTRY_CODE_NO = 'NO';
    const COUNTRY_CODE_PL = 'PL';
    const COUNTRY_CODE_PT = 'PT';
    const COUNTRY_CODE_RO = 'RO';
    const COUNTRY_CODE_RS = 'RS';
    const COUNTRY_CODE_RU = 'RU';
    const COUNTRY_CODE_SE = 'SE';
    const COUNTRY_CODE_SI = 'SI';
    const COUNTRY_CODE_SK = 'SK';
    const COUNTRY_CODE_SM = 'SM';
    const COUNTRY_CODE_UA = 'UA';
    const COUNTRY_CODE_VA = 'VA';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCountryCodeAllowableValues()
    {
        return [
            self::COUNTRY_CODE_AD,
            self::COUNTRY_CODE_AL,
            self::COUNTRY_CODE_AT,
            self::COUNTRY_CODE_BA,
            self::COUNTRY_CODE_BE,
            self::COUNTRY_CODE_BG,
            self::COUNTRY_CODE_BY,
            self::COUNTRY_CODE_CH,
            self::COUNTRY_CODE_CY,
            self::COUNTRY_CODE_CZ,
            self::COUNTRY_CODE_DE,
            self::COUNTRY_CODE_DK,
            self::COUNTRY_CODE_EE,
            self::COUNTRY_CODE_ES,
            self::COUNTRY_CODE_FI,
            self::COUNTRY_CODE_FO,
            self::COUNTRY_CODE_FR,
            self::COUNTRY_CODE_GB,
            self::COUNTRY_CODE_GI,
            self::COUNTRY_CODE_GR,
            self::COUNTRY_CODE_HR,
            self::COUNTRY_CODE_HU,
            self::COUNTRY_CODE_IE,
            self::COUNTRY_CODE_IM,
            self::COUNTRY_CODE_IS,
            self::COUNTRY_CODE_IT,
            self::COUNTRY_CODE_LI,
            self::COUNTRY_CODE_LT,
            self::COUNTRY_CODE_LU,
            self::COUNTRY_CODE_LV,
            self::COUNTRY_CODE_MC,
            self::COUNTRY_CODE_MD,
            self::COUNTRY_CODE_ME,
            self::COUNTRY_CODE_MK,
            self::COUNTRY_CODE_MT,
            self::COUNTRY_CODE_NL,
            self::COUNTRY_CODE_NO,
            self::COUNTRY_CODE_PL,
            self::COUNTRY_CODE_PT,
            self::COUNTRY_CODE_RO,
            self::COUNTRY_CODE_RS,
            self::COUNTRY_CODE_RU,
            self::COUNTRY_CODE_SE,
            self::COUNTRY_CODE_SI,
            self::COUNTRY_CODE_SK,
            self::COUNTRY_CODE_SM,
            self::COUNTRY_CODE_UA,
            self::COUNTRY_CODE_VA,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['country_code'] = isset($data['country_code']) ? $data['country_code'] : null;
        $this->container['zone'] = isset($data['zone']) ? $data['zone'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getCountryCodeAllowableValues();
        if (!is_null($this->container['country_code']) && !in_array($this->container['country_code'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'country_code', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets country_code
     *
     * @return string
     */
    public function getCountryCode()
    {
        return $this->container['country_code'];
    }

    /**
     * Sets country_code
     *
     * @param string $country_code country_code
     *
     * @return $this
     */
    public function setCountryCode($country_code)
    {
        $allowedValues = $this->getCountryCodeAllowableValues();
        if (!is_null($country_code) && !in_array($country_code, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'country_code', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['country_code'] = $country_code;

        return $this;
    }

    /**
     * Gets zone
     *
     * @return string
     */
    public function getZone()
    {
        return $this->container['zone'];
    }

    /**
     * Sets zone
     *
     * @param string $zone zone
     *
     * @return $this
     */
    public function setZone($zone)
    {
        $this->container['zone'] = $zone;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


