<?php
/**
 * CarrierApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fifty Truck API
 *
 * This is the API of fifty truck
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@fiftytruck.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CarrierApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CarrierApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addMarketplaceOffer
     *
     * Create new MarketplaceOffer.
     *
     */
    public function testAddMarketplaceOffer()
    {
    }

    /**
     * Test case for addOperator
     *
     * Create new operator.
     *
     */
    public function testAddOperator()
    {
    }

    /**
     * Test case for addRouteWaypointToSearchRoute
     *
     * Add new waypoint on given search route.
     *
     */
    public function testAddRouteWaypointToSearchRoute()
    {
    }

    /**
     * Test case for addShipperScore
     *
     * Set score for given shipper company name.
     *
     */
    public function testAddShipperScore()
    {
    }

    /**
     * Test case for addShippingOrderSearch
     *
     * Add shipping orders search.
     *
     */
    public function testAddShippingOrderSearch()
    {
    }

    /**
     * Test case for deleteMarketplaceOffer
     *
     * Delete given MarketplaceOffer and withdraw from all Marketplaces.
     *
     */
    public function testDeleteMarketplaceOffer()
    {
    }

    /**
     * Test case for deleteMarketplaceUser
     *
     * Delete marketplaceUser.
     *
     */
    public function testDeleteMarketplaceUser()
    {
    }

    /**
     * Test case for deleteOperator
     *
     * Delete operator.
     *
     */
    public function testDeleteOperator()
    {
    }

    /**
     * Test case for deleteShipperScore
     *
     * Delete ShipperScore.
     *
     */
    public function testDeleteShipperScore()
    {
    }

    /**
     * Test case for deleteShippingOrderSearch
     *
     * Delete shipping orders search.
     *
     */
    public function testDeleteShippingOrderSearch()
    {
    }

    /**
     * Test case for deleteShippingOrderSearchs
     *
     * Delete multiple shipping orders searches.
     *
     */
    public function testDeleteShippingOrderSearchs()
    {
    }

    /**
     * Test case for getConsultedShippingOrderResults
     *
     * Get ShippingOrderResults previously consulted.
     *
     */
    public function testGetConsultedShippingOrderResults()
    {
    }

    /**
     * Test case for getCountUnreadShippingOrderResult
     *
     * Get new offers count for each searches.
     *
     */
    public function testGetCountUnreadShippingOrderResult()
    {
    }

    /**
     * Test case for getDeletedMarketplaceOffers
     *
     * Get deleted marketplace offers.
     *
     */
    public function testGetDeletedMarketplaceOffers()
    {
    }

    /**
     * Test case for getEnabledMarketplaces
     *
     * Get enabled marketplaces.
     *
     */
    public function testGetEnabledMarketplaces()
    {
    }

    /**
     * Test case for getMarketplaceOfferDetail
     *
     * Get offer submitted on marketplaces.
     *
     */
    public function testGetMarketplaceOfferDetail()
    {
    }

    /**
     * Test case for getMarketplaceOffers
     *
     * Get offers submitted on marketplaces.
     *
     */
    public function testGetMarketplaceOffers()
    {
    }

    /**
     * Test case for getOperator
     *
     * Get operator by id.
     *
     */
    public function testGetOperator()
    {
    }

    /**
     * Test case for getOperators
     *
     * Get all operators.
     *
     */
    public function testGetOperators()
    {
    }

    /**
     * Test case for getSeizedShippingOrder
     *
     * Get seized ShippingOrder detail.
     *
     */
    public function testGetSeizedShippingOrder()
    {
    }

    /**
     * Test case for getSeizedShippingOrders
     *
     * Get seized ShippingOrders.
     *
     */
    public function testGetSeizedShippingOrders()
    {
    }

    /**
     * Test case for getShipperScores
     *
     * Get all shipper scores.
     *
     */
    public function testGetShipperScores()
    {
    }

    /**
     * Test case for getShippingOrderGrouping
     *
     * Get shipping order grouping with 2 results.
     *
     */
    public function testGetShippingOrderGrouping()
    {
    }

    /**
     * Test case for getShippingOrderResult
     *
     * Get shipping order detail.
     *
     */
    public function testGetShippingOrderResult()
    {
    }

    /**
     * Test case for getShippingOrderResultRoute
     *
     * Get shipping order route.
     *
     */
    public function testGetShippingOrderResultRoute()
    {
    }

    /**
     * Test case for getShippingOrderResults
     *
     * Get ShippingOrderResults from a given ShippingOrderSearch.
     *
     */
    public function testGetShippingOrderResults()
    {
    }

    /**
     * Test case for getShippingOrderResultsNotifications
     *
     * Get ShippingOrderResults previously pushed via notifications.
     *
     */
    public function testGetShippingOrderResultsNotifications()
    {
    }

    /**
     * Test case for getShippingOrderSearch
     *
     * Get shipping order search.
     *
     */
    public function testGetShippingOrderSearch()
    {
    }

    /**
     * Test case for getShippingOrderSearches
     *
     * Get shipping orders search and perform search query.
     *
     */
    public function testGetShippingOrderSearches()
    {
    }

    /**
     * Test case for getUnreadShippingOrderResults
     *
     * Get all unread ShippingOrderResults.
     *
     */
    public function testGetUnreadShippingOrderResults()
    {
    }

    /**
     * Test case for getUserMarketplace
     *
     * Get marketplaces on which user has entered his credentials.
     *
     */
    public function testGetUserMarketplace()
    {
    }

    /**
     * Test case for markAllResultsAsRead
     *
     * All ShippingOrderResult from all ShippingOrderSearch will be marked as read.
     *
     */
    public function testMarkAllResultsAsRead()
    {
    }

    /**
     * Test case for markAllResultsFromShippingOrderSearchAsRead
     *
     * All ShippingOrderResult from given ShippingOrderSearch will be marked as read.
     *
     */
    public function testMarkAllResultsFromShippingOrderSearchAsRead()
    {
    }

    /**
     * Test case for operatorLogin
     *
     * Login operator user.
     *
     */
    public function testOperatorLogin()
    {
    }

    /**
     * Test case for patchOperator
     *
     * Patch operator.
     *
     */
    public function testPatchOperator()
    {
    }

    /**
     * Test case for performPaginatedSearch
     *
     * Perform shippingOrderSearch and return results with scoring (which is performed synchronously).
     *
     */
    public function testPerformPaginatedSearch()
    {
    }

    /**
     * Test case for performSearchWithAsynchronousScoring
     *
     * Perform shippingOrderSearch and return results. Scoring is asynchronous and will be provided through websocket.
     *
     */
    public function testPerformSearchWithAsynchronousScoring()
    {
    }

    /**
     * Test case for publishMarketplaceOffer
     *
     * Publish given MarketplaceOffer.
     *
     */
    public function testPublishMarketplaceOffer()
    {
    }

    /**
     * Test case for putMarketplaceOffer
     *
     * Update a MarketplaceOffer.
     *
     */
    public function testPutMarketplaceOffer()
    {
    }

    /**
     * Test case for putShipperScore
     *
     * Change score for given shipper company name.
     *
     */
    public function testPutShipperScore()
    {
    }

    /**
     * Test case for putShippingOrderSearch
     *
     * Patch shipping orders search.
     *
     */
    public function testPutShippingOrderSearch()
    {
    }

    /**
     * Test case for refreshMarketplaceOffer
     *
     * Refresh given MarketplaceOffer on all Marketplaces.
     *
     */
    public function testRefreshMarketplaceOffer()
    {
    }

    /**
     * Test case for registerCarrier
     *
     * Register new Carrier.
     *
     */
    public function testRegisterCarrier()
    {
    }

    /**
     * Test case for searchComplements
     *
     * Search eventual complementary shipping orders.
     *
     */
    public function testSearchComplements()
    {
    }

    /**
     * Test case for seizeShippingOrderResult
     *
     * Seize existing shippingOrderResult.
     *
     */
    public function testSeizeShippingOrderResult()
    {
    }

    /**
     * Test case for sendMailContact
     *
     * Send contact mail to shipper.
     *
     */
    public function testSendMailContact()
    {
    }

    /**
     * Test case for toggleActivateShippingOrderSearch
     *
     * Enable/disable ShippingOrderSearch activation.
     *
     */
    public function testToggleActivateShippingOrderSearch()
    {
    }

    /**
     * Test case for triggerShippingOrderResultDialPhoneNumber
     *
     * Trigger a push to dial a phone number on a mobile device.
     *
     */
    public function testTriggerShippingOrderResultDialPhoneNumber()
    {
    }

    /**
     * Test case for updateOrCreateMarketplaceUser
     *
     * Add login/password user to connect to a marketplace.
     *
     */
    public function testUpdateOrCreateMarketplaceUser()
    {
    }

    /**
     * Test case for withdrawMarketplaceOffer
     *
     * Withdraw given MarketplaceOffer from given Marketplaces.
     *
     */
    public function testWithdrawMarketplaceOffer()
    {
    }
}
