/**
 * Fifty Truck API
 * This is the API of fifty truck
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@fiftytruck.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GeoJsonPoint { 
    /**
     * Model describing GeoJson Point object Used in other Swagger models as reference
     */
    type?: string;
    /**
     * Model describing GeoJson Point object Used in other Swagger models as reference
     */
    coordinates?: Array<number>;
}
