/**
 * Fifty Truck API
 * This is the API of fifty truck
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@fiftytruck.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SearchRouteComputedSearchZonesLoadingPointAddressZones { 
    countryCode?: SearchRouteComputedSearchZonesLoadingPointAddressZones.CountryCodeEnum;
    zone?: string;
}
export namespace SearchRouteComputedSearchZonesLoadingPointAddressZones {
    export type CountryCodeEnum = 'AD' | 'AL' | 'AT' | 'BA' | 'BE' | 'BG' | 'BY' | 'CH' | 'CY' | 'CZ' | 'DE' | 'DK' | 'EE' | 'ES' | 'FI' | 'FO' | 'FR' | 'GB' | 'GI' | 'GR' | 'HR' | 'HU' | 'IE' | 'IM' | 'IS' | 'IT' | 'LI' | 'LT' | 'LU' | 'LV' | 'MC' | 'MD' | 'ME' | 'MK' | 'MT' | 'NL' | 'NO' | 'PL' | 'PT' | 'RO' | 'RS' | 'RU' | 'SE' | 'SI' | 'SK' | 'SM' | 'UA' | 'VA';
    export const CountryCodeEnum = {
        AD: 'AD' as CountryCodeEnum,
        AL: 'AL' as CountryCodeEnum,
        AT: 'AT' as CountryCodeEnum,
        BA: 'BA' as CountryCodeEnum,
        BE: 'BE' as CountryCodeEnum,
        BG: 'BG' as CountryCodeEnum,
        BY: 'BY' as CountryCodeEnum,
        CH: 'CH' as CountryCodeEnum,
        CY: 'CY' as CountryCodeEnum,
        CZ: 'CZ' as CountryCodeEnum,
        DE: 'DE' as CountryCodeEnum,
        DK: 'DK' as CountryCodeEnum,
        EE: 'EE' as CountryCodeEnum,
        ES: 'ES' as CountryCodeEnum,
        FI: 'FI' as CountryCodeEnum,
        FO: 'FO' as CountryCodeEnum,
        FR: 'FR' as CountryCodeEnum,
        GB: 'GB' as CountryCodeEnum,
        GI: 'GI' as CountryCodeEnum,
        GR: 'GR' as CountryCodeEnum,
        HR: 'HR' as CountryCodeEnum,
        HU: 'HU' as CountryCodeEnum,
        IE: 'IE' as CountryCodeEnum,
        IM: 'IM' as CountryCodeEnum,
        IS: 'IS' as CountryCodeEnum,
        IT: 'IT' as CountryCodeEnum,
        LI: 'LI' as CountryCodeEnum,
        LT: 'LT' as CountryCodeEnum,
        LU: 'LU' as CountryCodeEnum,
        LV: 'LV' as CountryCodeEnum,
        MC: 'MC' as CountryCodeEnum,
        MD: 'MD' as CountryCodeEnum,
        ME: 'ME' as CountryCodeEnum,
        MK: 'MK' as CountryCodeEnum,
        MT: 'MT' as CountryCodeEnum,
        NL: 'NL' as CountryCodeEnum,
        NO: 'NO' as CountryCodeEnum,
        PL: 'PL' as CountryCodeEnum,
        PT: 'PT' as CountryCodeEnum,
        RO: 'RO' as CountryCodeEnum,
        RS: 'RS' as CountryCodeEnum,
        RU: 'RU' as CountryCodeEnum,
        SE: 'SE' as CountryCodeEnum,
        SI: 'SI' as CountryCodeEnum,
        SK: 'SK' as CountryCodeEnum,
        SM: 'SM' as CountryCodeEnum,
        UA: 'UA' as CountryCodeEnum,
        VA: 'VA' as CountryCodeEnum
    };
}
