/**
 * Fifty Truck API
 * This is the API of fifty truck
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@fiftytruck.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Route } from './Route';
import { RouteWaypoint } from './RouteWaypoint';
import { SearchRouteComputedSearchZones } from './SearchRouteComputedSearchZones';
import { SearchRouteSearchTerms } from './SearchRouteSearchTerms';


export interface SearchRoute { 
    id?: number;
    shippingOrderSearchId?: number;
    searchTerms?: SearchRouteSearchTerms;
    computedSearchZones?: SearchRouteComputedSearchZones;
    routeWithToll?: Route;
    routeWithoutToll?: Route;
    waypoints?: Array<RouteWaypoint>;
}
